/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/intakes-history`; params?: Router.UnknownInputParams; } | { pathname: `/intakes`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `/reset`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts/edit`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts/new`; params?: Router.UnknownInputParams; } | { pathname: `/reminders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/home`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/intakes-history`; params?: Router.UnknownOutputParams; } | { pathname: `/intakes`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/reminders`; params?: Router.UnknownOutputParams; } | { pathname: `/reset`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/emergency-contacts/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/emergency-contacts`; params?: Router.UnknownOutputParams; } | { pathname: `/emergency-contacts/new`; params?: Router.UnknownOutputParams; } | { pathname: `/reminders/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/home${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/intakes-history${`?${string}` | `#${string}` | ''}` | `/intakes${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/reminders${`?${string}` | `#${string}` | ''}` | `/reset${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/emergency-contacts/edit${`?${string}` | `#${string}` | ''}` | `/emergency-contacts${`?${string}` | `#${string}` | ''}` | `/emergency-contacts/new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/home`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/intakes-history`; params?: Router.UnknownInputParams; } | { pathname: `/intakes`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `/reset`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts/edit`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts`; params?: Router.UnknownInputParams; } | { pathname: `/emergency-contacts/new`; params?: Router.UnknownInputParams; } | `/reminders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/reminders/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
